In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime
import calendar
%matplotlib inline

In [6]:
def thirdWednsday(year, month):
    return calendar.Calendar().monthdatescalendar(year, month)[2][2]

In [38]:
def extract_rates(filepath):
    df = pd.read_csv(filepath, parse_dates=[3,4])
    index = df.StartDate.apply(lambda x : thirdWednsday(x.year, x.month))
    index[0] = df.StartDate[0]
    df.index = pd.to_datetime(index)
    #there is also convention about 3rd Wednsdey of contract month whatsoever
    df['IR'] = 1. - df.iloc[:,1]/100
    #correct libor row
    df.iloc[0, 5]=df.iloc[0,1]
    df['DF3m'] = np.exp(-df.IR)# * 90 / 360.)  # actual / 360 or should it be left as annual here?
    return df

In [39]:
rates = extract_rates('./data/USD rates.csv')
rates

,USD Rate MKT Data,Unnamed: 1,"Conv, adj",StartDate,EndDate,IR,DF3m
StartDate,,,,,,,
2021-10-28,Libor3m,0.001295,NaN,2021-10-28,2022-01-28,0.001295,0.998706
2021-12-15,EDZ1,99.810000,0.00014,2021-12-15,2022-03-15,0.001900,0.998102
2022-03-16,EDH2,99.785000,0.00073,2022-03-16,2022-06-16,0.002150,0.997852
2022-06-15,EDM2,99.680000,0.00165,2022-06-15,2022-09-15,0.003200,0.996805
2022-09-14,EDU2,99.520000,0.00287,2022-09-21,2022-12-21,0.004800,0.995212
2022-12-14,EDZ2,99.295000,0.00451,2022-12-21,2023-03-21,0.007050,0.992975
2023-03-15,EDH3,99.110000,0.00636,2023-03-15,2023-06-15,0.008900,0.991139
2023-06-14,EDM3,98.920000,0.00839,2023-06-21,2023-09-21,0.010800,0.989258
2023-09-13,EDU3,98.690000,0.01104,2023-09-20,2023-12-20,0.013100,0.986985
2023-12-13,EDZ3,98.585000,0.01380,2023-12-20,2024-03-20,0.014150,0.985950
2024-03-13,EDH4,98.490000,0.01688,2024-03-20,2024-06-20,0.015100,0.985013
2024-06-12,EDM4,98.410000,0.01387,2024-06-19,2024-09-19,0.015900,0.984226
2024-09-11,EDU4,98.335000,0.01696,2024-09-18,2024-12-18,0.016650,0.983488

So the questions are:

* Discount factors are calculated as $exp\{ -r \cdot (T-t)\}$, where T is 3months and r extracted from corresponding futures contract?